os: osx

stages:
  - PHP Versions Compilation Tests

jobs:
  include:
    - stage: PHP Versions Compilation Tests
      name: "8.0"
      script:
        - travis_wait 30 brew install valet-php@8.0 --build-from-source
    - script:
        - travis_wait 30 brew install valet-php@8.1 --build-from-source
      name: "8.1"
    - script:
        - travis_wait 30 brew install valet-php@7.4 --build-from-source
      name: "7.4"

before_script:
  - travis_retry brew tap henkrehorst/homebrew-php
